spring:
  application:
    name: GestioneImmobiliare
    version: 0.0.1-SNAPSHOT

  datasource:
    url: jdbc:mysql://localhost:3306/gestione_immobiliare?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      pool-name: HikariCP
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 600000      # 10 minuti
      connection-timeout: 30000 # 30 secondi
      max-lifetime: 1800000     # 30 minuti
      auto-commit: true
      transaction-isolation: TRANSACTION_READ_COMMITTED

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    open-in-view: true

server:
  port: 8080
  error:
    whitelabel:
      enabled: false

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG  # utile per il debug delle richieste REST

jwt:
  secret: una-chiave-segreta-molto-lunga
  expiration: 900000 # 15 minuti